name: release-all

on: workflow_dispatch

jobs:
  linux:
    uses: ./.github/workflows/release-linux.yml
  
  windows:
    uses: ./.github/workflows/release-windows.yml
    
  mac-osx:
    uses: ./.github/workflows/release-mac-osx.yml
    secrets: inherit